CREATE TABLE IF NOT EXISTS snapshots (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    year        INTEGER NOT NULL,
    stats_date  DATE    NOT NULL,
    fetched_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(year, stats_date)
);

CREATE TABLE IF NOT EXISTS team_standings (
    snapshot_id   INTEGER NOT NULL REFERENCES snapshots(id),
    league        TEXT    NOT NULL CHECK(league IN ('C','P')),
    rank          INTEGER NOT NULL,
    team          TEXT    NOT NULL,
    games         INTEGER,
    wins          INTEGER,
    losses        INTEGER,
    ties          INTEGER,
    win_pct       REAL,
    games_behind  REAL,
    PRIMARY KEY (snapshot_id, league, team)
);

CREATE TABLE IF NOT EXISTS team_batting (
    snapshot_id          INTEGER NOT NULL REFERENCES snapshots(id),
    league               TEXT    NOT NULL CHECK(league IN ('C','P')),
    team                 TEXT    NOT NULL,
    batting_avg          REAL,
    games                INTEGER,
    plate_appearances    INTEGER,
    at_bats              INTEGER,
    runs                 INTEGER,
    hits                 INTEGER,
    doubles              INTEGER,
    triples              INTEGER,
    home_runs            INTEGER,
    total_bases          INTEGER,
    rbi                  INTEGER,
    stolen_bases         INTEGER,
    caught_stealing      INTEGER,
    sacrifice_hits       INTEGER,
    sacrifice_flies      INTEGER,
    walks                INTEGER,
    intentional_walks    INTEGER,
    hit_by_pitch         INTEGER,
    strikeouts           INTEGER,
    grounded_into_dp     INTEGER,
    slugging_pct         REAL,
    on_base_pct          REAL,
    PRIMARY KEY (snapshot_id, league, team)
);

CREATE TABLE IF NOT EXISTS team_pitching (
    snapshot_id          INTEGER NOT NULL REFERENCES snapshots(id),
    league               TEXT    NOT NULL CHECK(league IN ('C','P')),
    team                 TEXT    NOT NULL,
    era                  REAL,
    games                INTEGER,
    wins                 INTEGER,
    losses               INTEGER,
    saves                INTEGER,
    holds                INTEGER,
    hold_points          INTEGER,
    complete_games       INTEGER,
    shutouts             INTEGER,
    no_walks             INTEGER,
    win_pct              REAL,
    batters_faced        INTEGER,
    innings_pitched      REAL,
    hits                 INTEGER,
    home_runs            INTEGER,
    walks                INTEGER,
    intentional_walks    INTEGER,
    hit_by_pitch         INTEGER,
    strikeouts           INTEGER,
    wild_pitches         INTEGER,
    balks                INTEGER,
    runs                 INTEGER,
    earned_runs          INTEGER,
    PRIMARY KEY (snapshot_id, league, team)
);

CREATE TABLE IF NOT EXISTS team_fielding (
    snapshot_id                INTEGER NOT NULL REFERENCES snapshots(id),
    league                     TEXT    NOT NULL CHECK(league IN ('C','P')),
    team                       TEXT    NOT NULL,
    fielding_avg               REAL,
    games                      INTEGER,
    chances                    INTEGER,
    putouts                    INTEGER,
    assists                    INTEGER,
    errors                     INTEGER,
    double_plays_participated  INTEGER,
    double_plays_team          INTEGER,
    passed_balls               INTEGER,
    PRIMARY KEY (snapshot_id, league, team)
);

CREATE TABLE IF NOT EXISTS player_batting (
    snapshot_id          INTEGER NOT NULL REFERENCES snapshots(id),
    league               TEXT    NOT NULL CHECK(league IN ('C','P')),
    player               TEXT    NOT NULL,
    team                 TEXT,
    rank                 INTEGER,
    batting_avg          REAL,
    games                INTEGER,
    plate_appearances    INTEGER,
    at_bats              INTEGER,
    runs                 INTEGER,
    hits                 INTEGER,
    doubles              INTEGER,
    triples              INTEGER,
    home_runs            INTEGER,
    total_bases          INTEGER,
    rbi                  INTEGER,
    stolen_bases         INTEGER,
    caught_stealing      INTEGER,
    sacrifice_hits       INTEGER,
    sacrifice_flies      INTEGER,
    walks                INTEGER,
    intentional_walks    INTEGER,
    hit_by_pitch         INTEGER,
    strikeouts           INTEGER,
    grounded_into_dp     INTEGER,
    slugging_pct         REAL,
    on_base_pct          REAL,
    PRIMARY KEY (snapshot_id, league, player)
);

CREATE TABLE IF NOT EXISTS player_pitching (
    snapshot_id          INTEGER NOT NULL REFERENCES snapshots(id),
    league               TEXT    NOT NULL CHECK(league IN ('C','P')),
    player               TEXT    NOT NULL,
    team                 TEXT,
    rank                 INTEGER,
    era                  REAL,
    games                INTEGER,
    wins                 INTEGER,
    losses               INTEGER,
    saves                INTEGER,
    holds                INTEGER,
    hold_points          INTEGER,
    complete_games       INTEGER,
    shutouts             INTEGER,
    no_walks             INTEGER,
    win_pct              REAL,
    batters_faced        INTEGER,
    innings_pitched      REAL,
    hits                 INTEGER,
    home_runs            INTEGER,
    walks                INTEGER,
    intentional_walks    INTEGER,
    hit_by_pitch         INTEGER,
    strikeouts           INTEGER,
    wild_pitches         INTEGER,
    balks                INTEGER,
    runs                 INTEGER,
    earned_runs          INTEGER,
    PRIMARY KEY (snapshot_id, league, player)
);

CREATE TABLE IF NOT EXISTS player_fielding (
    snapshot_id          INTEGER NOT NULL REFERENCES snapshots(id),
    league               TEXT    NOT NULL CHECK(league IN ('C','P')),
    position             TEXT    NOT NULL,
    player               TEXT    NOT NULL,
    team                 TEXT,
    rank                 INTEGER,
    fielding_avg         REAL,
    games                INTEGER,
    putouts              INTEGER,
    assists              INTEGER,
    errors               INTEGER,
    double_plays         INTEGER,
    passed_balls         INTEGER,
    PRIMARY KEY (snapshot_id, league, position, player)
);